Fix built messge datasource streaming exception
ballerina-platform/module-ballerina-http pull request #374
Opened 2021-05-07 12:29 UTC by chamil321

## Purpose
> Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1333

## Examples

## Checklist
- [ ] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests

2021-05-08 10:44 UTC, ayeshLK requested changes

2021-05-08 10:44 UTC, ayeshLK commented on http-native/src/main/java/org/ballerinalang/net/http/nativeimpl/ExternHttpDataSourceBuilder.java
> +            return;
```suggestion
        if (Objects.nonNull(dataSource)) {
            return;
```

2021-05-08 10:44 UTC, ayeshLK commented on http-native/src/main/java/org/ballerinalang/net/http/nativeimpl/ExternHttpDataSourceBuilder.java
>          if (httpCarbonMessage != null) {
```suggestion
        if (Objects.nonNull(httpCarbonMessage)) {
```

2021-05-10 03:37 UTC, ldclakmal approved these changes

2021-05-10 06:07 UTC, merged